---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: false
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.rb"
  - "**.slim"
  - "**.coffee"
  - "**.js"
  - "**.jsx"
exclude_paths:
  - app/assets/javascripts/routes.js
  - config/
  - db/
  - spec/
  - vendor/
