language: ruby
rvm:
  - 2.3.0
services:
  - postgresql
  - redis-server
addons:	
  postgresql: "9.4"
before_script:
  - psql -c 'create database cherashev_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:schema:load