env:
  global:
    - CC_TEST_REPORTER_ID=f419708620ed858fc25934516fd83abbcac1aee18be0fec8526095d86aab247a
language: ruby
rvm:
  - 2.4.2
  - 2.5.0
services:
  - postgresql
  - redis-server
addons:
  postgresql: 9.6
before_script:
  - psql -c 'create database cherashev_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:schema:load
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
