language: ruby
rvm:
  - 2.3.0
services:
  - postgresql
  - redis-server
addons:
  postgresql: "9.4"
  code_climate:
    repo_token: f419708620ed858fc25934516fd83abbcac1aee18be0fec8526095d86aab247a
before_script:
  - psql -c 'create database cherashev_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:schema:load
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
