language: ruby
rvm:
  - 2.3.0
services:
  - postgresql
addons:	
  postgresql: "9.4"
before_script:
  - psql -c 'create database cherashev_test;' -U postgres
script: 
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/