version: '3'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Production.Dockerfile
      args:
        rails_env: production
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - redis
    environment:
      APP_HOME: /var/www/cherashev
      RAILS_ENV: production
      RAILS_MAX_THREADS: 5
      WEB_CONCURRENCY: 1
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SECRET_KEY_BASE: ''

  web:
    image: nginx:1.15.2-alpine
    restart: always
    networks:
      - frontend
    depends_on:
      - app
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/certs
      - public:$APP_HOME/public
    ports:
      - 80:80
      - 443:443
    environment:
      APP_HOME: /var/www/cherashev

  db:
    restart: always

  redis:
    restart: always
