version: '3'

services:
  db:
    restart: always

  redis:
    restart: always

  app:
    restart: always
    build:
      context: .
      dockerfile: Production.Dockerfile
      args:
        rails_env: production
    ports:
      - 4242:4242
    networks:
      - frontend
      - backend
    volumes:
      - uploads:/var/www/cherashev/public/uploads
    command: /bin/sh bin/start
    depends_on:
      - db
      - redis
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 1024M
      restart_policy:
        condition: on-failure
    environment:
      RAILS_ENV: production
      RAILS_MAX_THREADS: 5
      WEB_CONCURRENCY: 4
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SECRET_KEY_BASE: ''

  web:
    image: nginx:1.15.0-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    networks:
      - frontend
