version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Development.Dockerfile
      args:
        rails_env: development
    command: /bin/sh bin/start
    ports:
      - 4242:4242
    environment:
      APP_HOME: /var/www/cherashev
    volumes:
      - .:/var/www/cherashev
      - /Users/drwg/src/_ruby/bundle:/var/bundle
