version: '3'

services:
  app:
    image: cherashev/cherashev-app:latest
    restart: on-failure
    ports:
      - "4242"
    networks:
      - frontend
      - backend
    volumes:
      - public:$APP_HOME/public
      - uploads:$APP_HOME/public/uploads
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
      WEB_CONCURRENCY: 4
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SECRET_KEY_BASE: ''

  db:
    image: postgres:10.4-alpine
    restart: on-failure
    ports:
      - "5432"
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata

  redis:
    image: redis:4.0-alpine
    restart: on-failure
    ports:
      - "6379"
    networks:
      - backend
    volumes:
      - redis-data:/data

networks:
  frontend:
  backend:

volumes:
  bundle:
  public:
  uploads:
  db-data:
  redis-data:
