version: '3'

services:
  db:
    image: postgres:10.3-alpine
    restart: on-failure
    ports:
      - "6379"
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata

  redis:
    image: redis:4.0-alpine
    restart: on-failure
    ports:
      - "6379"
    networks:
      - backend
    volumes:
      - redis-data:/data

  app:
    image: cherashev-dev-alpine
    restart: on-failure
    build:
      context: .
      dockerfile: Development.Dockerfile
      args:
        rails_env: development
    ports:
      - 4242:4242
    networks:
      - frontend
      - backend
    volumes:
      - .:/var/www/cherashev
      - uploads:/var/www/cherashev/public/uploads
      - bundle:/var/bundle
    command: /bin/sh bin/start
    depends_on:
      - db
      - redis
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure
    environment:
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
      WEB_CONCURRENCY: 4
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SECRET_KEY_BASE: ''

  web:
    image: nginx:1.12.2-alpine
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    networks:
      - frontend

networks:
  frontend:
  backend:

volumes:
  bundle:
  uploads:
  db-data:
  redis-data:
