default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 }.to_i %>
  host: <%= ENV.fetch("POSTGRES_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { 'postgres' } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'postgres' } %>
development:
  <<: *default
  database: cherashev_development
test:
  <<: *default
  database: cherashev_test
production:
  <<: *default
  database: cherashev_production
