default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: None
  pool: 5
development:
  <<: *default
  database: cherashev_development
test:
  <<: *default
  database: cherashev_test
production:
  <<: *default
  database: cherashev_production
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  