default: &default
  namespace: cherashev
  key: _cherashev_session
  db: 2
  host: <%= ENV.fetch("REDIS_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("REDIS_PORT") { 6379 } %>
development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
  password: <%= ENV.fetch("REDIS_PASSWORD") { '' } %>
