#= require turbolinks
#= require jquery
#= require jquery_ujs
#= require nprogress
#= require nprogress-turbolinks
#= require bootstrap
#= require bootstrap-wysihtml5
#= require bootstrap-wysihtml5/locales/ru-RU
#= require js-routes
#= require_tree .
#= require_slef
